/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Capteur (void);
GtkWidget* create_Ajouter (void);
GtkWidget* create_Afficher (void);
GtkWidget* create_Modifier (void);
GtkWidget* create_Supprimer (void);
GtkWidget* create_Controle (void);
GtkWidget* create_Date (void);
GtkWidget* create_CheckOut (void);
