/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Capteur (void)
{
  GtkWidget *Capteur;
  GtkWidget *fixed1;
  GtkWidget *image1;
  GtkWidget *button3_modifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *button5_controle;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *button4_supprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *button1_ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *button2_afficher;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *label1;

  Capteur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Capteur), _("Capteur"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Capteur), fixed1);

  image1 = create_pixmap (Capteur, "2742.jpg_wh860.jpeg");
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed1), image1, 0, 0);
  gtk_widget_set_size_request (image1, 856, 528);
  gtk_misc_set_alignment (GTK_MISC (image1), 0.43, 0.54);

  button3_modifier = gtk_button_new ();
  gtk_widget_show (button3_modifier);
  gtk_fixed_put (GTK_FIXED (fixed1), button3_modifier, 348, 465);
  gtk_widget_set_size_request (button3_modifier, 110, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3_modifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  button5_controle = gtk_button_new ();
  gtk_widget_show (button5_controle);
  gtk_fixed_put (GTK_FIXED (fixed1), button5_controle, 564, 465);
  gtk_widget_set_size_request (button5_controle, 110, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5_controle), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Controle"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  button4_supprimer = gtk_button_new ();
  gtk_widget_show (button4_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed1), button4_supprimer, 456, 465);
  gtk_widget_set_size_request (button4_supprimer, 110, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4_supprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-cut", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  button1_ajouter = gtk_button_new ();
  gtk_widget_show (button1_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), button1_ajouter, 132, 465);
  gtk_widget_set_size_request (button1_ajouter, 110, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1_ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  button2_afficher = gtk_button_new ();
  gtk_widget_show (button2_afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), button2_afficher, 240, 465);
  gtk_widget_set_size_request (button2_afficher, 110, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2_afficher), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-zoom-fit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("\n<span foreground=\"black\" ><b>BIENVENUE </b></span>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 216, 80);
  gtk_widget_set_size_request (label1, 352, 56);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_CENTER);
  gtk_misc_set_alignment (GTK_MISC (label1), 0.52, 0.59);

  g_signal_connect ((gpointer) button3_modifier, "clicked",
                    G_CALLBACK (on_button3_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5_controle, "clicked",
                    G_CALLBACK (on_button5_controle_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_supprimer, "clicked",
                    G_CALLBACK (on_button4_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_ajouter, "clicked",
                    G_CALLBACK (on_button1_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_afficher, "clicked",
                    G_CALLBACK (on_button2_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Capteur, Capteur, "Capteur");
  GLADE_HOOKUP_OBJECT (Capteur, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Capteur, image1, "image1");
  GLADE_HOOKUP_OBJECT (Capteur, button3_modifier, "button3_modifier");
  GLADE_HOOKUP_OBJECT (Capteur, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Capteur, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Capteur, image4, "image4");
  GLADE_HOOKUP_OBJECT (Capteur, label4, "label4");
  GLADE_HOOKUP_OBJECT (Capteur, button5_controle, "button5_controle");
  GLADE_HOOKUP_OBJECT (Capteur, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Capteur, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Capteur, image6, "image6");
  GLADE_HOOKUP_OBJECT (Capteur, label6, "label6");
  GLADE_HOOKUP_OBJECT (Capteur, button4_supprimer, "button4_supprimer");
  GLADE_HOOKUP_OBJECT (Capteur, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Capteur, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Capteur, image5, "image5");
  GLADE_HOOKUP_OBJECT (Capteur, label5, "label5");
  GLADE_HOOKUP_OBJECT (Capteur, button1_ajouter, "button1_ajouter");
  GLADE_HOOKUP_OBJECT (Capteur, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Capteur, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Capteur, image2, "image2");
  GLADE_HOOKUP_OBJECT (Capteur, label2, "label2");
  GLADE_HOOKUP_OBJECT (Capteur, button2_afficher, "button2_afficher");
  GLADE_HOOKUP_OBJECT (Capteur, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Capteur, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Capteur, image3, "image3");
  GLADE_HOOKUP_OBJECT (Capteur, label3, "label3");
  GLADE_HOOKUP_OBJECT (Capteur, label1, "label1");

  return Capteur;
}

GtkWidget*
create_Ajouter (void)
{
  GtkWidget *Ajouter;
  GtkWidget *fixed2;
  GtkWidget *entrynombre;
  GtkWidget *entrylieu;
  GtkWidget *entrytype;
  GtkWidget *entrymarque;
  GtkWidget *hseparator1;
  GtkWidget *image26;
  GtkWidget *label40;
  GtkWidget *Nombre;
  GtkWidget *Emplacement;
  GtkWidget *Marque;
  GtkWidget *Type;
  GtkWidget *button1_enregister;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image7;
  GtkWidget *label12;
  GtkWidget *button3_retour;
  GtkWidget *image9;
  GtkWidget *hseparator2;
  GtkWidget *button2_date;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label13;
  GtkWidget *label41;

  Ajouter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter), _("Ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Ajouter), fixed2);

  entrynombre = gtk_entry_new ();
  gtk_widget_show (entrynombre);
  gtk_fixed_put (GTK_FIXED (fixed2), entrynombre, 300, 200);
  gtk_widget_set_size_request (entrynombre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynombre), 8226);

  entrylieu = gtk_entry_new ();
  gtk_widget_show (entrylieu);
  gtk_fixed_put (GTK_FIXED (fixed2), entrylieu, 300, 250);
  gtk_widget_set_size_request (entrylieu, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrylieu), 8226);

  entrytype = gtk_entry_new ();
  gtk_widget_show (entrytype);
  gtk_fixed_put (GTK_FIXED (fixed2), entrytype, 304, 304);
  gtk_widget_set_size_request (entrytype, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytype), 8226);

  entrymarque = gtk_entry_new ();
  gtk_widget_show (entrymarque);
  gtk_fixed_put (GTK_FIXED (fixed2), entrymarque, 300, 357);
  gtk_widget_set_size_request (entrymarque, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymarque), 8226);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed2), hseparator1, 64, 416);
  gtk_widget_set_size_request (hseparator1, 16, 16);

  image26 = create_pixmap (Ajouter, "42-incorporate-farm-feature-min.jpeg");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed2), image26, 0, 0);
  gtk_widget_set_size_request (image26, 848, 520);

  label40 = gtk_label_new (_("<span foreground=\"black\" ><b>Ajouter un capteur :</b></span>"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed2), label40, 200, 128);
  gtk_widget_set_size_request (label40, 376, 40);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  Nombre = gtk_label_new (_("<span foreground=\"green\" ><b>Nombre</b></span>"));
  gtk_widget_show (Nombre);
  gtk_fixed_put (GTK_FIXED (fixed2), Nombre, 152, 200);
  gtk_widget_set_size_request (Nombre, 136, 25);
  gtk_label_set_use_markup (GTK_LABEL (Nombre), TRUE);

  Emplacement = gtk_label_new (_("<span foreground=\"green\" ><b>Emplacement</b></span>"));
  gtk_widget_show (Emplacement);
  gtk_fixed_put (GTK_FIXED (fixed2), Emplacement, 168, 256);
  gtk_widget_set_size_request (Emplacement, 120, 16);
  gtk_label_set_use_markup (GTK_LABEL (Emplacement), TRUE);

  Marque = gtk_label_new (_("<span foreground=\"green\" ><b>Marque</b></span>"));
  gtk_widget_show (Marque);
  gtk_fixed_put (GTK_FIXED (fixed2), Marque, 184, 312);
  gtk_widget_set_size_request (Marque, 96, 17);
  gtk_label_set_use_markup (GTK_LABEL (Marque), TRUE);

  Type = gtk_label_new (_("<span foreground=\"green\" ><b>Type</b></span>"));
  gtk_widget_show (Type);
  gtk_fixed_put (GTK_FIXED (fixed2), Type, 184, 360);
  gtk_widget_set_size_request (Type, 104, 17);
  gtk_label_set_use_markup (GTK_LABEL (Type), TRUE);

  button1_enregister = gtk_button_new ();
  gtk_widget_show (button1_enregister);
  gtk_fixed_put (GTK_FIXED (fixed2), button1_enregister, 488, 280);
  gtk_widget_set_size_request (button1_enregister, 128, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button1_enregister), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image7 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox6), image7, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox6), label12, FALSE, FALSE, 0);

  button3_retour = gtk_button_new ();
  gtk_widget_show (button3_retour);
  gtk_fixed_put (GTK_FIXED (fixed2), button3_retour, 800, 8);
  gtk_widget_set_size_request (button3_retour, 48, 48);

  image9 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (button3_retour), image9);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed2), hseparator2, 264, 440);
  gtk_widget_set_size_request (hseparator2, 600, 16);

  button2_date = gtk_button_new ();
  gtk_widget_show (button2_date);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_date, 744, 464);
  gtk_widget_set_size_request (button2_date, 66, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button2_date), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("GO"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox7), label13, FALSE, FALSE, 0);

  label41 = gtk_label_new (_("<span foreground=\"red\" ><b>Ajouter une date</b></span>"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed2), label41, 608, 464);
  gtk_widget_set_size_request (label41, 311, 73);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  g_signal_connect ((gpointer) button1_enregister, "clicked",
                    G_CALLBACK (on_button1_enregister_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3_retour, "clicked",
                    G_CALLBACK (on_button3_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_date, "clicked",
                    G_CALLBACK (on_button2_date_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter, Ajouter, "Ajouter");
  GLADE_HOOKUP_OBJECT (Ajouter, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Ajouter, entrynombre, "entrynombre");
  GLADE_HOOKUP_OBJECT (Ajouter, entrylieu, "entrylieu");
  GLADE_HOOKUP_OBJECT (Ajouter, entrytype, "entrytype");
  GLADE_HOOKUP_OBJECT (Ajouter, entrymarque, "entrymarque");
  GLADE_HOOKUP_OBJECT (Ajouter, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (Ajouter, image26, "image26");
  GLADE_HOOKUP_OBJECT (Ajouter, label40, "label40");
  GLADE_HOOKUP_OBJECT (Ajouter, Nombre, "Nombre");
  GLADE_HOOKUP_OBJECT (Ajouter, Emplacement, "Emplacement");
  GLADE_HOOKUP_OBJECT (Ajouter, Marque, "Marque");
  GLADE_HOOKUP_OBJECT (Ajouter, Type, "Type");
  GLADE_HOOKUP_OBJECT (Ajouter, button1_enregister, "button1_enregister");
  GLADE_HOOKUP_OBJECT (Ajouter, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Ajouter, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Ajouter, image7, "image7");
  GLADE_HOOKUP_OBJECT (Ajouter, label12, "label12");
  GLADE_HOOKUP_OBJECT (Ajouter, button3_retour, "button3_retour");
  GLADE_HOOKUP_OBJECT (Ajouter, image9, "image9");
  GLADE_HOOKUP_OBJECT (Ajouter, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (Ajouter, button2_date, "button2_date");
  GLADE_HOOKUP_OBJECT (Ajouter, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Ajouter, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Ajouter, image8, "image8");
  GLADE_HOOKUP_OBJECT (Ajouter, label13, "label13");
  GLADE_HOOKUP_OBJECT (Ajouter, label41, "label41");

  return Ajouter;
}

GtkWidget*
create_Afficher (void)
{
  GtkWidget *Afficher;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *button1_check;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image10;
  GtkWidget *label15;
  GtkWidget *label14;
  GtkWidget *button18;
  GtkWidget *image27;

  Afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Afficher), _("Afficher"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Afficher), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 248, 160);
  gtk_widget_set_size_request (treeview1, 328, 200);

  button1_check = gtk_button_new ();
  gtk_widget_show (button1_check);
  gtk_fixed_put (GTK_FIXED (fixed3), button1_check, 336, 392);
  gtk_widget_set_size_request (button1_check, 136, 29);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button1_check), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox8), image10, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox8), label15, FALSE, FALSE, 0);

  label14 = gtk_label_new (_("<span foreground=\"green\" ><b>Nos informations :</b></span>"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed3), label14, 328, 112);
  gtk_widget_set_size_request (label14, 192, 25);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  button18 = gtk_button_new ();
  gtk_widget_show (button18);
  gtk_fixed_put (GTK_FIXED (fixed3), button18, 8, 648);
  gtk_widget_set_size_request (button18, 160, 109);

  image27 = create_pixmap (Afficher, "index.jpeg");
  gtk_widget_show (image27);
  gtk_container_add (GTK_CONTAINER (button18), image27);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button1_check, "clicked",
                    G_CALLBACK (on_button1_check_clicked),
                    NULL);
  g_signal_connect ((gpointer) button18, "clicked",
                    G_CALLBACK (on_button18_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Afficher, Afficher, "Afficher");
  GLADE_HOOKUP_OBJECT (Afficher, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Afficher, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Afficher, button1_check, "button1_check");
  GLADE_HOOKUP_OBJECT (Afficher, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Afficher, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Afficher, image10, "image10");
  GLADE_HOOKUP_OBJECT (Afficher, label15, "label15");
  GLADE_HOOKUP_OBJECT (Afficher, label14, "label14");
  GLADE_HOOKUP_OBJECT (Afficher, button18, "button18");
  GLADE_HOOKUP_OBJECT (Afficher, image27, "image27");

  return Afficher;
}

GtkWidget*
create_Modifier (void)
{
  GtkWidget *Modifier;
  GtkWidget *fixed4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkWidget *button12;
  GtkWidget *image14;
  GtkWidget *button2back;
  GtkWidget *image15;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;

  Modifier = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifier), _("Modifier"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Modifier), fixed4);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 296, 144);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 296, 192);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 296, 240);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 296, 296);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed4), button12, 328, 336);
  gtk_widget_set_size_request (button12, 66, 29);

  image14 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_container_add (GTK_CONTAINER (button12), image14);

  button2back = gtk_button_new ();
  gtk_widget_show (button2back);
  gtk_fixed_put (GTK_FIXED (fixed4), button2back, 568, 344);
  gtk_widget_set_size_request (button2back, 288, 181);

  image15 = create_pixmap (Modifier, "index.jpeg");
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (button2back), image15);

  label18 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\" ><b>Nombre</b></span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 136, 152);
  gtk_widget_set_size_request (label18, 120, 16);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  label19 = gtk_label_new (_("<span foreground=\"green\" ><b>Emlacement</b></span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 160, 200);
  gtk_widget_set_size_request (label19, 112, 17);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  label20 = gtk_label_new (_("<span foreground=\"green\" ><b>Type</b></span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 160, 240);
  gtk_widget_set_size_request (label20, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  label21 = gtk_label_new (_("<span foreground=\"green\" ><b>Marque</b></span>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 152, 296);
  gtk_widget_set_size_request (label21, 80, 17);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  label22 = gtk_label_new (_("<span foreground=\"black\" ><b>Modifier les informations</b></span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 240, 64);
  gtk_widget_set_size_request (label22, 264, 57);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2back, "clicked",
                    G_CALLBACK (on_button2back_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifier, Modifier, "Modifier");
  GLADE_HOOKUP_OBJECT (Modifier, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Modifier, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Modifier, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (Modifier, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (Modifier, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Modifier, button12, "button12");
  GLADE_HOOKUP_OBJECT (Modifier, image14, "image14");
  GLADE_HOOKUP_OBJECT (Modifier, button2back, "button2back");
  GLADE_HOOKUP_OBJECT (Modifier, image15, "image15");
  GLADE_HOOKUP_OBJECT (Modifier, label18, "label18");
  GLADE_HOOKUP_OBJECT (Modifier, label19, "label19");
  GLADE_HOOKUP_OBJECT (Modifier, label20, "label20");
  GLADE_HOOKUP_OBJECT (Modifier, label21, "label21");
  GLADE_HOOKUP_OBJECT (Modifier, label22, "label22");

  return Modifier;
}

GtkWidget*
create_Supprimer (void)
{
  GtkWidget *Supprimer;
  GtkWidget *fixed5;
  GtkWidget *entry9;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkWidget *entry12;
  GtkWidget *button13;
  GtkWidget *image16;
  GtkWidget *label23;
  GtkWidget *label25;
  GtkWidget *label24;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *hseparator4;
  GtkWidget *button14_backe;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image17;
  GtkWidget *label28;

  Supprimer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Supprimer), _("Supprimer"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Supprimer), fixed5);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed5), entry9, 272, 120);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed5), entry10, 272, 184);
  gtk_widget_set_size_request (entry10, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed5), entry11, 272, 248);
  gtk_widget_set_size_request (entry11, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  entry12 = gtk_entry_new ();
  gtk_widget_show (entry12);
  gtk_fixed_put (GTK_FIXED (fixed5), entry12, 272, 312);
  gtk_widget_set_size_request (entry12, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12), 8226);

  button13 = gtk_button_new ();
  gtk_widget_show (button13);
  gtk_fixed_put (GTK_FIXED (fixed5), button13, 296, 368);
  gtk_widget_set_size_request (button13, 74, 29);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (button13), image16);

  label23 = gtk_label_new (_("<span foreground=\"black\" ><b>Supprimer un capteur</b></span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed5), label23, 248, 64);
  gtk_widget_set_size_request (label23, 216, 16);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  label25 = gtk_label_new (_("<span foreground=\"green\" ><b>emplacement</b></span>\n"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 136, 192);
  gtk_widget_set_size_request (label25, 120, 16);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  label24 = gtk_label_new (_("<span foreground=\"green\" ><b>Nombre</b></span>\n"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 104, 128);
  gtk_widget_set_size_request (label24, 168, 16);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label26 = gtk_label_new (_("<span foreground=\"green\" ><b>Type</b></span>\n"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 168, 264);
  gtk_widget_set_size_request (label26, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  label27 = gtk_label_new (_("<span foreground=\"green\" ><b>Marque</b></span>"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 128, 312);
  gtk_widget_set_size_request (label27, 112, 25);
  gtk_label_set_use_markup (GTK_LABEL (label27), TRUE);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_fixed_put (GTK_FIXED (fixed5), hseparator4, 0, 568);
  gtk_widget_set_size_request (hseparator4, 648, 32);

  button14_backe = gtk_button_new ();
  gtk_widget_show (button14_backe);
  gtk_fixed_put (GTK_FIXED (fixed5), button14_backe, 568, 584);
  gtk_widget_set_size_request (button14_backe, 80, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button14_backe), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image17 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox9), image17, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("\n"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox9), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button13, "clicked",
                    G_CALLBACK (on_button13_clicked),
                    NULL);
  g_signal_connect ((gpointer) button14_backe, "clicked",
                    G_CALLBACK (on_button14_backe_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer, Supprimer, "Supprimer");
  GLADE_HOOKUP_OBJECT (Supprimer, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Supprimer, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (Supprimer, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (Supprimer, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (Supprimer, entry12, "entry12");
  GLADE_HOOKUP_OBJECT (Supprimer, button13, "button13");
  GLADE_HOOKUP_OBJECT (Supprimer, image16, "image16");
  GLADE_HOOKUP_OBJECT (Supprimer, label23, "label23");
  GLADE_HOOKUP_OBJECT (Supprimer, label25, "label25");
  GLADE_HOOKUP_OBJECT (Supprimer, label24, "label24");
  GLADE_HOOKUP_OBJECT (Supprimer, label26, "label26");
  GLADE_HOOKUP_OBJECT (Supprimer, label27, "label27");
  GLADE_HOOKUP_OBJECT (Supprimer, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (Supprimer, button14_backe, "button14_backe");
  GLADE_HOOKUP_OBJECT (Supprimer, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Supprimer, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Supprimer, image17, "image17");
  GLADE_HOOKUP_OBJECT (Supprimer, label28, "label28");

  return Supprimer;
}

GtkWidget*
create_Controle (void)
{
  GtkWidget *Controle;
  GtkWidget *fixed6;
  GtkWidget *hseparator5;
  GtkWidget *button17;
  GtkWidget *image21;
  GtkWidget *Label38;
  GtkWidget *button16;
  GtkWidget *image20;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *label39;

  Controle = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Controle), _("Controle"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Controle), fixed6);

  hseparator5 = gtk_hseparator_new ();
  gtk_widget_show (hseparator5);
  gtk_fixed_put (GTK_FIXED (fixed6), hseparator5, 0, 448);
  gtk_widget_set_size_request (hseparator5, 840, 16);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed6), button17, 736, 464);
  gtk_widget_set_size_request (button17, 74, 29);

  image21 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_container_add (GTK_CONTAINER (button17), image21);

  Label38 = gtk_label_new (_("<span foreground=\"red\" ><b></b></span>"));
  gtk_widget_show (Label38);
  gtk_fixed_put (GTK_FIXED (fixed6), Label38, 80, 232);
  gtk_widget_set_size_request (Label38, 424, 144);
  gtk_label_set_use_markup (GTK_LABEL (Label38), TRUE);
  gtk_misc_set_padding (GTK_MISC (Label38), 11, 0);

  button16 = gtk_button_new ();
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed6), button16, 256, 176);
  gtk_widget_set_size_request (button16, 192, 37);
  gtk_button_set_focus_on_click (GTK_BUTTON (button16), FALSE);

  image20 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_container_add (GTK_CONTAINER (button16), image20);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("En paine"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton2, 448, 184);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));
  gtk_toggle_button_set_inconsistent (GTK_TOGGLE_BUTTON (radiobutton2), TRUE);
  gtk_toggle_button_set_mode (GTK_TOGGLE_BUTTON (radiobutton2), FALSE);

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Fonctionne"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton1, 140, 184);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));
  gtk_toggle_button_set_inconsistent (GTK_TOGGLE_BUTTON (radiobutton1), TRUE);
  gtk_toggle_button_set_mode (GTK_TOGGLE_BUTTON (radiobutton1), FALSE);

  label39 = gtk_label_new (_("<span foreground=\"green\" ><b>Fonctionnement technique</b></span>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed6), label39, 168, 88);
  gtk_widget_set_size_request (label39, 336, 41);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Controle, Controle, "Controle");
  GLADE_HOOKUP_OBJECT (Controle, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Controle, hseparator5, "hseparator5");
  GLADE_HOOKUP_OBJECT (Controle, button17, "button17");
  GLADE_HOOKUP_OBJECT (Controle, image21, "image21");
  GLADE_HOOKUP_OBJECT (Controle, Label38, "Label38");
  GLADE_HOOKUP_OBJECT (Controle, button16, "button16");
  GLADE_HOOKUP_OBJECT (Controle, image20, "image20");
  GLADE_HOOKUP_OBJECT (Controle, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (Controle, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (Controle, label39, "label39");

  return Controle;
}

GtkWidget*
create_Date (void)
{
  GtkWidget *Date;
  GtkWidget *fixed7;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label32;
  GtkWidget *combobox2;
  GtkWidget *button14;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image18;
  GtkWidget *label35;
  GtkWidget *sortie;
  GtkWidget *button15;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image19;
  GtkWidget *label37;
  GtkWidget *combobox1;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label33;
  GtkWidget *label34;

  Date = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Date), _("Date"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (Date), fixed7);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton1, 120, 80);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton2, 304, 80);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (1, 2005, 2024, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed7), spinbutton3, 472, 80);
  gtk_widget_set_size_request (spinbutton3, 56, 24);

  label32 = gtk_label_new ("");
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed7), label32, 56, 272);
  gtk_widget_set_size_request (label32, 49, 17);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox2, 200, 296);
  gtk_widget_set_size_request (combobox2, 33, 31);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed7), button14, 416, 232);
  gtk_widget_set_size_request (button14, 74, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button14), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image18 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox10), image18, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox10), label35, FALSE, FALSE, 0);

  sortie = gtk_label_new ("");
  gtk_widget_show (sortie);
  gtk_fixed_put (GTK_FIXED (fixed7), sortie, 520, 224);
  gtk_widget_set_size_request (sortie, 112, 49);

  button15 = gtk_button_new ();
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed7), button15, 424, 368);
  gtk_widget_set_size_request (button15, 74, 29);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button15), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image19 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox11), image19, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Done"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox11), label37, FALSE, FALSE, 0);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed7), combobox1, 152, 224);
  gtk_widget_set_size_request (combobox1, 200, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Temperature"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("humidit\303\251"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("autre"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), "");

  label29 = gtk_label_new (_("<span foreground=\"Blue\" ><b>jour</b></span>"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed7), label29, 48, 80);
  gtk_widget_set_size_request (label29, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label29), TRUE);

  label30 = gtk_label_new (_("<span foreground=\"blue\" ><b>mois</b></span>"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed7), label30, 224, 80);
  gtk_widget_set_size_request (label30, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label30), TRUE);

  label31 = gtk_label_new (_("<span foreground=\"blue\" ><b>annee</b></span>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed7), label31, 400, 80);
  gtk_widget_set_size_request (label31, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  label33 = gtk_label_new (_("<span foreground=\"green\" ><b>Type</b></span>"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed7), label33, 40, 232);
  gtk_widget_set_size_request (label33, 96, 17);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  label34 = gtk_label_new (_("<span foreground=\"green\" ><b>Lieu</b></span>"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed7), label34, 32, 304);
  gtk_widget_set_size_request (label34, 104, 17);
  gtk_label_set_use_markup (GTK_LABEL (label34), TRUE);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Date, Date, "Date");
  GLADE_HOOKUP_OBJECT (Date, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Date, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (Date, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Date, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (Date, label32, "label32");
  GLADE_HOOKUP_OBJECT (Date, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (Date, button14, "button14");
  GLADE_HOOKUP_OBJECT (Date, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Date, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Date, image18, "image18");
  GLADE_HOOKUP_OBJECT (Date, label35, "label35");
  GLADE_HOOKUP_OBJECT (Date, sortie, "sortie");
  GLADE_HOOKUP_OBJECT (Date, button15, "button15");
  GLADE_HOOKUP_OBJECT (Date, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Date, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Date, image19, "image19");
  GLADE_HOOKUP_OBJECT (Date, label37, "label37");
  GLADE_HOOKUP_OBJECT (Date, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (Date, label29, "label29");
  GLADE_HOOKUP_OBJECT (Date, label30, "label30");
  GLADE_HOOKUP_OBJECT (Date, label31, "label31");
  GLADE_HOOKUP_OBJECT (Date, label33, "label33");
  GLADE_HOOKUP_OBJECT (Date, label34, "label34");

  return Date;
}

GtkWidget*
create_CheckOut (void)
{
  GtkWidget *CheckOut;
  GtkWidget *fixed8;
  GtkWidget *button1_done;
  GtkWidget *image13;
  GtkWidget *button4_retour;
  GtkWidget *image12;
  GtkWidget *hseparator6;
  GtkWidget *label16;
  GtkWidget *checkbutton1;
  GtkWidget *checkbutton2;
  GtkWidget *label17;

  CheckOut = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (CheckOut), _("CheckOut"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (CheckOut), fixed8);

  button1_done = gtk_button_new ();
  gtk_widget_show (button1_done);
  gtk_fixed_put (GTK_FIXED (fixed8), button1_done, 328, 136);
  gtk_widget_set_size_request (button1_done, 66, 29);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_container_add (GTK_CONTAINER (button1_done), image13);

  button4_retour = gtk_button_new ();
  gtk_widget_show (button4_retour);
  gtk_fixed_put (GTK_FIXED (fixed8), button4_retour, 496, 424);
  gtk_widget_set_size_request (button4_retour, 66, 29);

  image12 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (button4_retour), image12);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_fixed_put (GTK_FIXED (fixed8), hseparator6, 8, 408);
  gtk_widget_set_size_request (hseparator6, 560, 24);

  label16 = gtk_label_new (_("<span foreground=\"black\" ><b>Verifier les informations</b></span>"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed8), label16, 176, 56);
  gtk_widget_set_size_request (label16, 184, 16);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("Disponibles"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton1, 144, 112);
  gtk_widget_set_size_request (checkbutton1, 118, 24);
  gtk_toggle_button_set_mode (GTK_TOGGLE_BUTTON (checkbutton1), FALSE);

  checkbutton2 = gtk_check_button_new_with_mnemonic (_("Maquantes"));
  gtk_widget_show (checkbutton2);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton2, 144, 168);
  gtk_widget_set_size_request (checkbutton2, 118, 24);
  gtk_toggle_button_set_mode (GTK_TOGGLE_BUTTON (checkbutton2), FALSE);

  label17 = gtk_label_new (_("<span foreground=\"red\" ><b></b></span>"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed8), label17, 0, 216);
  gtk_widget_set_size_request (label17, 568, 168);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  g_signal_connect ((gpointer) button1_done, "clicked",
                    G_CALLBACK (on_button1_done_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_retour, "clicked",
                    G_CALLBACK (on_button4_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (CheckOut, CheckOut, "CheckOut");
  GLADE_HOOKUP_OBJECT (CheckOut, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (CheckOut, button1_done, "button1_done");
  GLADE_HOOKUP_OBJECT (CheckOut, image13, "image13");
  GLADE_HOOKUP_OBJECT (CheckOut, button4_retour, "button4_retour");
  GLADE_HOOKUP_OBJECT (CheckOut, image12, "image12");
  GLADE_HOOKUP_OBJECT (CheckOut, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (CheckOut, label16, "label16");
  GLADE_HOOKUP_OBJECT (CheckOut, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (CheckOut, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (CheckOut, label17, "label17");

  return CheckOut;
}

